version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: fundinfra
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/fundinfra
      JWT_SECRET: supersecretdev
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: sh -c "npm install && npm run dev"

volumes:
  db_data:
